Repository flagscript/flagscript-organization-setup, pull requests merged in 2024-08, with the labels that each got.

#2 Add github actions.
  .cfnlintrc
  .github/workflows/release.yml
  .github/workflows/test.yml
  .gitignore
  .husky/pre-commit
  .releaserc.json
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  package.json
  pnpm-lock.yaml
Labels: cicd

#4 Add state bucket replication
  templates/flagscript-organization-setup.yml
Labels: enhancement

#6 Fix semantic release, publish missed feat
  .github/workflows/release.yml
Labels: bug, enhancement, cicd

#7 Fix semantic release (again)
  .github/workflows/release.yml
Labels: bug

#8 Fix semantic release again
  .github/workflows/release.yml
Labels: bug, cicd
